version: '3'

services:
  node:
    build:
      context: .
      dockerfile: DockerfileNode
    command: sh -c "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/twitter_good/node_modules
    ports:
      - "3000:3000"
  
  django:
    build:
      context: .
      dockerfile: DockerfileDjango
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/usr/src/app/django:cached
    ports: 
      - "8000:8000"